# Generated by Django 2.2.1 on 2019-05-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hello_models',
            table='APPppp',

        ),
    ]
